### ISSUE TITLE
Segmentation fault if translateRecursivelyAt() finds new functions to analyze

### ISSUE THREAD

**Issue by 0o52** [repzret/dagger#18] opened 2017-04-26 21:43 UTC
There is a Segmentation fault in dagger if translateRecursivelyAt() finds new function, i think.

The problem occures in line 221 of llvm-dec.cpp:
```
  for (auto &F : MCM->funcs())
    translateRecursivelyAt(F->getStartAddr(), *DT, *MCM, OD.get(), MOS.get());
```

We get an interator-range from MCM->funcs() (which is in fact a vector of unique_ptrs that hold all the MCFunctions MCM found) and iterate over it. But translateRecursiveAt() updates the list of this vector of functions which we are iterating if it finds a new one. If this occures our iterator-range gets invalid and we access invalid memory with our reference F.

The code in DCTranslatorUtils.cpp (ranslateRecursiveAt()) who is updating the vector of functions is the following (lines 63 to 72):
```
    // Now look for the function if it was already in the module.
    MCFunction *MCFN = MCM.findFunctionAt(Addr);
    // If it wasn't, we need to disassemble it.
    if (!MCFN) {
      if (!MCOD)
        report_fatal_error(("Unable to translate unknown function at " +
                            utohexstr(Addr) + " without a disassembler!")
                               .c_str());
      MCFN = MCOD->createFunction(&MCM, Addr);
    }
```

If we do not execute MCOD->createFunction() here to create a new function in MCM, then no problem will arise, but we do not analyse the new function we found.

For a quick fix, I replaced the two lines in llvm-dec as follow:
```
  bool newFunctions = true; // we have functions in MCM to progress
  unsigned int fnCount = 0; // total number of functions in MCM
  std::vector<std::unique_ptr<MCFunction>> functionList; // copy of MCM-fn-list

  while(newFunctions){
    functionList.clear(); // make sure, that the list is empty
    for (auto &F : MCM->funcs())
      functionList.push_back(std::move(F)); // copy all functions from MCM
    if (fnCount != functionList.size()){ // on new functions progress them
      fnCount = functionList.size();
      for (auto &F : functionList){
        if(F.get() != nullptr) // do not process the same functions again
          translateRecursivelyAt(
              F->getStartAddr(), *DT, *MCM, OD.get(), MOS.get());
      }
    }else{
      newFunctions = false;
    }
  }
```

Now it seems to work properly, but for sure, this is very ugly code and we have to find a better solution.

What do you think about create a member-variable in MCM who holds the number of functions it found and if we add a new one to MCM it increments. In llvm-dec we could check this number every time before we invoke translateRecursivelyAt() and if a change occures we start again with our interation. If such a solution would be ok for you i could make a pull request or an patch or something like that for this to fix it.

**Comment by repzret** [comment] 2017-05-01 16:35
Thanks for the detailed investigation!

I'm a bit surprised this occurs: in llvm-dec, the module CFG is built ahead of time ('buildModule'), so by the time we get to 'translateRecursivelyAt', there shouldn't be anything else to discover (the only source of new functions is MCFN->callees(), which is statically determined).

The ability to disassemble new discovered functions should only be necessary in the dynamic mode, where we never try to build the complete module CFG. 

Do you have a reproducer?  I'll try to craft a testcase on my side.

But regardless, iterator invalidation is nasty so let's try to make it completely impossible.
I think it can be fixed in a simpler way: 'translateRecursivelyAt' is, as the name indicates, recursive, so it will already translate anything it discovers.  So this just needs to copy the addresses of the MCM functions to a list of entrypoints and pass that to 'translateRecursivelyAt'.  (and that can be made nice and readable if translateRecursivelyAt took an 'ArrayRef<uint64_t>' instead of a single 'uint64_t').

**Comment by repzret** [comment] 2017-05-01 16:38
(and to give you an idea, this is what I'm imagining: https://gist.github.com/repzret/da7bab1af7424a60b77e19ddf9ea4e1a)

**Comment by 0o52** [comment] 2017-05-01 18:02
While i tried to give you an reproducer, I realized, that this could be hard to do. The files this error occures where binaries created from source which were deleted in the meantime. I rebuilded them and tried it again, but the error was gone. The resulting binaries should be the same because a few days ago this error occured reproducible on these files.
Then I remembered, that I updated my local branch of dagger two days ago from an outdated version (sry for this). Could this be the reason that I could not reproduce this error? I am trying to build an older version of dagger now and test it again. I hope the build will finish today to give you a quick update.

**Comment by 0o52** [comment] 2017-05-01 20:01
Ok, I reverted to Revision 08cab70 from 22.03.17 at 17:36 and there i can reproduce it. If you are interested to investigate this on an old dagger-version i could send you my x86 ELF-File per Mail.

**Comment by repzret** [comment] 2017-05-02 14:26
> Ok, I reverted to Revision 08cab70 from 22.03.17 at 17:36 and there i can reproduce it.
Huh, interesting.  I haven't spotted any related changes since then.

> If you are interested to investigate this on an old dagger-version i could send you my x86 ELF-File per Mail.
Please do, I'll take a look.

**Comment by repzret** [comment] 2017-05-05 17:24
I can reproduce on that commit!  So, it turns out that MCObjectDisassembler::buildCFG (which is ancient code overdue for a cleanup..) sometimes misses the call targets and it's only later when we actually try to translate the whole thing that we end up discovering callees.

It's easy to fix buildCFG, but I'll do some extra refactoring as well. I'll "fix" the range-for-loop defensively regardless.

Thanks again for the reproducer.

**Comment by 0o52** [comment] 2017-05-05 19:48
fyi: the bug/Segmentation Fault is back in fc517980f3548d733189747b01298be626346715
You should be able to reproduce with the same reproducer.

**Closed** 2017-05-11 17:09 UTC
